version: "3.1"

services:
  product-service:
    container_name: product_service
    build: ./product-service/
    ports:
      - 8081:8080
    volumes:
      - ./product-service:/app

  cart-service:
    container_name: cart_service
    build: ./cart-service/
    ports:
      - 8082:8080
    volumes:
      - ./cart-service:/app

  user-service:
    container_name: user_service
    build: ./user-service/
    ports:
      - 8083:8080
    volumes:
      - ./user-service:/app

  mariadb:
    image: mariadb
    restart: always
    ports:
      - 8090:3306
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: kasun
      MARIADB_PASSWORD: 1234
    volumes:
      - ./db_volume:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8091:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  db_volume:
